plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.plugin.compose'
}

android {
    namespace 'io.github.rikumi.lyrichelper'
    compileSdk 37
    defaultConfig {
        applicationId 'io.github.rikumi.lyrichelper'
        minSdk 26
        targetSdk 35
        versionCode 20003
        versionName '2.0.3'
    }
    buildTypes { release { minifyEnabled false } }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlin { jvmToolchain(21) }
    buildFeatures { compose true }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.activity:activity-compose:1.10.1'
    implementation 'androidx.compose.ui:ui:1.7.8'
    implementation 'androidx.compose.ui:ui-tooling-preview:1.7.8'
    implementation 'androidx.compose.material3:material3:1.3.1'
    implementation 'androidx.lifecycle:lifecycle-runtime-compose:2.8.7'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0'
    implementation 'top.yukonga.miuix.kmp:miuix-ui:0.9.0'
    implementation 'top.yukonga.miuix.kmp:miuix-preference:0.9.0'
    implementation 'top.yukonga.miuix.kmp:miuix-icons:0.9.0'
    implementation 'org.jetbrains.androidx.navigationevent:navigationevent-compose:1.0.1'
    implementation 'com.android.volley:volley:1.2.1'
    testImplementation 'junit:junit:4.13.2'
}
